Repository EAPD-DRB/OG-ZAF, pull requests merged in 2023-01, with the labels that each got.

#27 Removed openssl from setup.py list
  setup.py
Labels: bug

#14 Update demographics.py and other files
  .github/workflows/deploy_docs.yml
  .github/workflows/docs_check.yml
  .gitignore
  README.md
  docs/book/content/api/demographics.rst
  environment.yml
  examples/run_og_zaf.py
  ogzaf/calibrate.py
  ogzaf/data/demographic/india_pop_data.csv
  ogzaf/data/demographic/un_zaf_deaths.csv
  ogzaf/data/demographic/un_zaf_fert.csv
  ogzaf/data/demographic/un_zaf_infmort.csv
  ogzaf/data/demographic/un_zaf_mort.csv
  ogzaf/data/demographic/un_zaf_pop.csv
  ogzaf/demographics.py
Labels: enhancement

#24 Update r_gov_scale and r_gov_shift variables in macro_params.py
  ogzaf/macro_params.py
  ogzaf/ogzaf_default_parameters.json
Labels: enhancement

#28 Update get_e_orig() with an adjustment by age calibration for ZAF
  .github/workflows/deploy_docs.yml
  .github/workflows/docs_check.yml
  README.md
  docs/book/_config.yml
  docs/book/content/calibration/demographics.md
  docs/book/content/calibration/earnings.md
  docs/book/content/calibration/exogenous_parameters.md
  examples/run_og_zaf.py
  ogzaf/calibrate.py
  ogzaf/income.py
  ogzaf/ogzaf_default_parameters.json
Labels: data
